services:
  generator:
    build: ./generator
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - web-output:/output
    restart: unless-stopped

  web:
    build: ./web
    depends_on:
      - generator
    ports:
      - "${PORT:-6498}:80"
    volumes:
      - web-output:/var/graph:ro
    restart: unless-stopped
    labels:
      - webproxy.subdomain=view

volumes:
  web-output:
